databaseChangeLog:
  - changeSet:
      id: load-configuration-data-01
      author: msp
      changes:
        - loadData:
            encoding: UTF-8
            file: db/data/dodcore_base_trait_rule.csv
            quotchar:  ''''
            separator:  ;
            tableName: base_trait_rule
        - loadData:
            encoding: UTF-8
            file: db/data/dodcore_character_template.csv
            quotchar:  ''''
            separator:  ;
            tableName: character_template
        - loadData:
            encoding: UTF-8
            file: db/data/dodcore_character_template_base_trait_rules.csv
            quotchar:  ''''
            separator:  ;
            tableName: character_template_base_trait_rules
  - changeSet:
        id: load-configuration-data-02
        author: msp
        changes:
          - loadData:
              encoding: UTF-8
              file: db/data/dodcore_race.csv
              quotchar:  ''''
              separator:  ;
              tableName: race
  - changeSet:
      id: load-configuration-data-03
      author: msp
      changes:
        - loadData:
            encoding: UTF-8
            file: db/data/dodcore_base_body.csv
            quotchar:  ''''
            separator:  ;
            tableName: base_body
  - changeSet:
      id: load-configuration-data-04
      author: msp
      changes:
        - loadData:
            encoding: UTF-8
            file: db/data/dodcore_character.csv
            quotchar:  ''''
            separator:  ;
            tableName: dodcharacter
