databaseChangeLog:
  - changeSet:
      id: load-configuration-data-06
      author: msp
      changes:
        - loadData:
            encoding: UTF-8
            file: db/data/config/skill_hand_to_hand.csv
            quotchar: ''''
            separator: ;
            tableName: skill