version: "3.9"
services:

  ui:
    image: "macp/dod-ui:latest"
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - api
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:80 || exit 1"
      start_period: "10s"

  api:
    image: "macp/dod:latest"
    ports:
      - "8090:8090"
      - "5005:5005"
    depends_on:
      - db
      - security
#    entrypoint: ["/__cacert_entrypoint.sh"]
#    command: ["sh -c 'java -cp $$( cat /app/jib-classpath-file ) $$( cat /app/jib-main-class-file )'"]
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-default,prod}"
      USE_SYSTEM_CA_CERTS: 1
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8090/dodgame/health || exit 1"
      start_period: "200s"
#    volumes:
#      - ./security/dodgame.jks:/tmp/dodgame.jks

  security:
    image: "macp/dod-keycloak:22.0.1"
    build:
      context: ./security/keycloak
    entrypoint: ''
    command: "wait-for-it.sh -t 0 db:3306 -- /opt/keycloak/bin/kc.sh start-dev  --http-port=8181 --hostname-admin-url=http://security:8181 --hostname-debug=true --import-realm"
    ports:
      - "8181:8181"
#      - "8443:8443"
    depends_on:
      - db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
      KC_DB_URL_DATABASE: keycloakDB
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: example
      KC_DB_TIMEOUT_WAIT_SECONDS: 600
      KC_HEALTH_ENABLED: "true"
    volumes:
      - "./security/keycloak/new-realm-export:/tmp/keycloak-export"
    healthcheck:
      test: "curl -k --silent --fail http://localhost:8181/health || exit 1"
      start_period: "200s"

  db:
    image: "mysql:8.1"
    volumes:
      - "./mysql/init-scripts:/docker-entrypoint-initdb.d"
      - "./mysql/config/my.cnf:/etc/mysql/my.cnf"
      - "db_data:/var/lib/mysql:rw"
    restart: "always"
    command: mysqld --character-set-server=UTF8MB3
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: example
      MYSQL_DEFAULT_AUTH: caching_sha2_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      TZ: "UTC"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -hlocalhost -usa -pexample  | grep -i 'mysqld is alive' || exit 1"
      start_period: "20s"
volumes:
  db_data: {}
