version: "3.9"
services:
  char:
    image: "macp/dod:latest"
    ports:
      - "8080:8080"
  db:
    image: "mysql:8.0"
    volumes:
      - "db_data:/var/lib/mysql"
    restart: "always"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dodcore
      MYSQL_USER: sa
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
volumes:
  db_data: {}
