version: "3.9"
services:

  ui:
    image: "macp/dod-ui:latest"
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - api

  api:
    image: "macp/dod:latest"
    ports:
      - "8090:8090"
      - "5005:5005"
    depends_on:
      - db
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8090/actuator/health || exit 1"
      start_period: "30s"

  db:
    image: "mysql:8.0"
    volumes:
      - "db_data:/var/lib/mysql"
    restart: "always"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dodcore
      MYSQL_USER: sa
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -hlocalhost -usa -pexample  | grep -i 'mysqld is alive' || exit 1"
      start_period: "20s"

volumes:
  db_data: {}
