package dk.pekilidi.dodgame.selenium;// Generated by Selenium IDE

import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

class LoginDeleteVokanLogoutTest {

  static JavascriptExecutor js;
  private static WebDriver driver;
  private static Map<String, Object> vars;

  @BeforeAll
  public static void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterAll
  public static void tearDown() {
    driver.quit();
  }

  @Test
  void loginDeleteVokanLogout() {
    // Test name: login_delete_Vokan_logout
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://ui:8081/");
    // 2 | setWindowSize | 1312x1455 | 
    driver.manage().window().setSize(new Dimension(1312, 1455));
    // 3 | mouseOver | css=.MuiTab-root > .MuiSvgIcon-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTab-root > .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | css=.MuiTab-root > .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector(".MuiTab-root > .MuiSvgIcon-root")).click();
    // 5 | mouseOut | css=.MuiTab-root > .MuiSvgIcon-root | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 7 | type | id=username | msp
    driver.findElement(By.id("username")).sendKeys("msp");
    // 8 | type | id=password | msp123
    driver.findElement(By.id("password")).sendKeys("msp123");
    // 9 | click | id=kc-login | 
    driver.findElement(By.id("kc-login")).click();
    // 10 | click | css=.MuiImageListItem-root:nth-child(2) .MuiImageListItemBar-title | 
    driver.findElement(By.cssSelector(".MuiImageListItem-root:nth-child(2) .MuiImageListItemBar-title")).click();
    // 11 | mouseOver | css=.MuiCardHeader-subheader | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiCardHeader-subheader"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | css=.MuiCardHeader-subheader | 
    driver.findElement(By.cssSelector(".MuiCardHeader-subheader")).click();
    // 13 | mouseOver | css=.Mui-selected | 
    {
      WebElement element = driver.findElement(By.cssSelector(".Mui-selected"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | click | css=.Mui-selected | 
    driver.findElement(By.cssSelector(".Mui-selected")).click();
    // 15 | mouseOut | css=.Mui-selected | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 16 | click | css=.MuiIconButton-root > .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector(".MuiIconButton-root > .MuiSvgIcon-root")).click();
    // 17 | click | css=.css-nt05bc | 
    driver.findElement(By.cssSelector(".css-nt05bc")).click();
    // 18 | click | id=kc-logout | 
    driver.findElement(By.id("kc-logout")).click();
  }
}
