spring:
  application:
    name: dod
  cloud:
    config:
      enabled: false
  cache:
    type: simple
  liquibase:
    contexts: test
    drop-first: true

  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:mysql://db:3306/dodcore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: example
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        show_sql: true
        use_sql_comments: true
        format_sql: true
        cache:
          use_second_level_cache: false
    open-in-view: true
