version: '2'
services:
    dod-app:
        image: dod
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://dod-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=dod
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    dod-mongodb:
        extends:
            file: mongodb.yml
            service: dod-mongodb
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
