export enum CharacterState {
  NEW = "NEW",
  BASE_TRAITS_SET = "BASE_TRAITS_SET",
  AGE_GROUP_SET = "AGE_GROUP_SET",
  TOTAL_HP_SET = "TOTAL_HP_SET",
  BODY_PART_HP_SET = "BODY_PART_HP_SET",
  DAMAGE_BONUS_SET = "",
  INIT_COMPLETE = "INIT_COMPLETE",
  READY_TO_PLAY = "READY_TO_PLAY",
  DEAD = "DEAD"
}