import dk.dodgame.data.CharacterDTO
import dk.dodgame.domain.character.model.CharacterState
import dk.dodgame.util.Dice
import dk.dodgame.domain.action.model.SkillTrainingAction
import dk.dodgame.domain.action.model.Type
import dk.dodgame.domain.action.model.ActionResult
import dk.dodgame.domain.skill.SkillService
import dk.dodgame.domain.skill.SkillNotFoundException
import dk.dodgame.data.SkillDTO
import dk.dodgame.domain.changerequest.model.ChangeStatus
import dk.dodgame.util.rules.RulesUtil
import dk.dodgame.domain.character.model.BaseTraitName
import java.time.LocalDate
import java.time.LocalDateTime
import dk.dodgame.data.CharacterSkillDTO
import dk.dodgame.data.CharacterSkillDTO
import dk.dodgame.util.Dice

rule "Determine single source action outcome - success"
  ruleflow-group "award-experience"
  salience -50
  no-loop
  when
    ssAction : SkillTrainingAction( type == Type.SKILL_TRAINING && actionResult == ActionResult.SUCCESS )
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY ) from ssAction.actor
  then
    CharacterSkillDTO characterSkill = character.getSkills().get( ssAction.getSkillKey() );
    LocalDateTime today = LocalDateTime.now();
    if (characterSkill.getLastUsed() == null || today.isBefore(characterSkill.getLastUsed())){
      int exp = character.getSkills().get( ssAction.getSkillKey() ).getExperience();
      character.getSkills().get( ssAction.getSkillKey() ).setExperience( exp + 1 );
    }
    update(ssAction);
end;

rule "Determine single source action outcome - masterful success"
  ruleflow-group "award-experience"
  salience -50
  no-loop
  when
    ssAction : SkillTrainingAction( type == Type.SKILL_TRAINING && actionResult == ActionResult.MASTERFUL )
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY ) from ssAction.actor
  then
    CharacterSkillDTO characterSkill = character.getSkills().get( ssAction.getSkillKey() );
    int exp = character.getSkills().get( ssAction.getSkillKey() ).getExperience();
    character.getSkills().get( ssAction.getSkillKey() ).setExperience( exp + Dice.roll("1t3") );
    update(ssAction);
end;

rule "Determine single source action outcome - perfect success"
  ruleflow-group "award-experience"
  salience -50
  no-loop
  when
    ssAction : SkillTrainingAction( type == Type.SKILL_TRAINING && actionResult == ActionResult.PERFECT )
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY ) from ssAction.actor
  then
    CharacterSkillDTO characterSkill = character.getSkills().get( ssAction.getSkillKey() );
    int exp = character.getSkills().get( ssAction.getSkillKey() ).getExperience();
    character.getSkills().get( ssAction.getSkillKey() ).setExperience( exp + Dice.roll("1t4") );
    update(ssAction);
end;