import dk.dodgame.domain.changerequest.model.ChangeStatusLabel
import dk.dodgame.domain.changerequest.model.ChangeStatus
import dk.dodgame.domain.changerequest.model.ChangeRequest
import dk.dodgame.domain.changerequest.model.ChangeType
import dk.dodgame.domain.character.model.CharacterState
import dk.dodgame.data.CharacterDTO
import dk.dodgame.domain.skill.SkillService
import dk.dodgame.data.CharacterSkillDTO
import dk.dodgame.domain.skill.SkillKey
import dk.dodgame.domain.skill.SkillNotFoundException

global SkillService skillService;
global CharacterSkillDTO charSkill;

rule "Validate character state - for skill change"
  ruleflow-group "skill-change"
  salience 100
  no-loop
  when
    changeRequest : ChangeRequest( changeType == ChangeType.SKILL_CHANGE && status == ChangeStatus.PENDING )
    character : CharacterDTO( state != CharacterState.READY_TO_PLAY)
  then
    changeRequest.setStatusLabel(ChangeStatusLabel.WRONG_CHARACTER_STATE);
    changeRequest.setStatus(ChangeStatus.REJECTED);
    update(changeRequest)
end;

rule "Validate change request - for skill change"
  ruleflow-group "skill-change"
  salience 100
  no-loop
  when
    changeRequest : ChangeRequest( changeType == ChangeType.SKILL_CHANGE && status == ChangeStatus.PENDING )
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY )
  then
    String skillKey = ((SkillKey) changeRequest.getChangeKey()).getKeyValue();
    charSkill = character.getSkills().get(skillKey);
    if(charSkill == null){
      changeRequest.setStatusLabel(ChangeStatusLabel.USER_DOES_NOT_HAVE_SKILL);
      changeRequest.setStatus(ChangeStatus.REJECTED);
    }
    if(charSkill != null){
      drools.getKieRuntime().setGlobal("charSkill", charSkill);
      skillCost = SkillService.calculatePriceForFVIncrease(character, skillKey, (Integer) changeRequest.getModifier());
      drools.getKieRuntime().setGlobal("skillCost", skillCost);
      if( charSkill.getExperience() < skillCost ){
        changeRequest.setStatusLabel(ChangeStatusLabel.INSUFFICIENT_EXP_POINTS);
        changeRequest.setStatus(ChangeStatus.REJECTED);
      }
    }
    changeRequest.setStatus(ChangeStatus.VALIDATED);
    update(changeRequest)
end;

rule "Recalculate Dodge Skill - for skill increase"
  ruleflow-group "new-skill"
  salience 80
  no-loop
  when
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY )
    changeRequest : ChangeRequest( changeType == ChangeType.SKILL_CHANGE && status == ChangeStatus.VALIDATED )
  then
    String skillKey = ((SkillKey) changeRequest.getChangeKey()).getKeyValue();
    if(skillKey.equalsIgnoreCase("primary.weapon")){
        CharacterSkillDTO dodgeSkill = character.getSkills().get("dodge");
        if(dodgeSkill != null){
          character.updateFv("dodge", Math.ceilDiv((Integer)changeRequest.getModifier() + dodgeSkill.getFv(), 2));
        }
    }
end;

rule "Increase skill FV"
  ruleflow-group "skill-change"
  salience 50
  no-loop
  when
    changeRequest : ChangeRequest( changeType == ChangeType.SKILL_CHANGE && status == ChangeStatus.VALIDATED )
    character : CharacterDTO( state == CharacterState.READY_TO_PLAY )
  then
    skillCost = (Integer) drools.getKieRuntime().getGlobal("skillCost");
    charSkill = (CharacterSkillDTO) drools.getKieRuntime().getGlobal("charSkill");
    if( charSkill != null && skillCost != null ){
      charSkill.setFv(charSkill.getFv() + (Integer) changeRequest.getModifier());
      charSkill.setExperience(charSkill.getExperience() - skillCost);
      changeRequest.setStatus(ChangeStatus.APPROVED);
      changeRequest.setStatusLabel(ChangeStatusLabel.OK_FV_INCREASED);
    } else {
      changeRequest.setStatusLabel(ChangeStatusLabel.CHANGE_REJECTED_UNKNOWN_REASON);
      changeRequest.setStatus(ChangeStatus.REJECTED);
    }
    drools.getKieRuntime().setGlobal("skillCost", null);
    drools.getKieRuntime().setGlobal("charSkill", null);
    update(changeRequest)
end;