server:
  port: 8090
  servlet:
    context-path: /dodgame
spring:
  mvc:
    static-path-pattern: /docs/**
  output:
    ansi:
      enabled: DETECT
  application:
    name: dod
  cache:
    type: simple
  liquibase:
    contexts: test
    drop-first: true
  sql:
    init:
      continue-on-error: true

  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:mysql://db:3306/dodcoreDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: example
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 300000 #5m was #20s
      idle-timeout: 300000 #5m
      max-lifetime: 600000 #10m
      initialization-fail-timeout: -1
      validation-timeout: 1000 #1s
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        show_sql: true
        use_sql_comments: true
        format_sql: true
        globally_quoted_identifiers: true
        cache:
          use_second_level_cache: false
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://security:8181/realms/dodgame
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    cors:
#      allowed-headers: "*"
#      allowed-credentials: true
#      allowed-origins: "*"
#      allowed-methods: "*"
#      exposed-headers: "ETag, Content-Disposition"
jwt:
  auth:
    converter:
      resource-id: dodgame-api
      principal-attribute: preferred_username
management:
  endpoints:
    web:
      exposure:
        include: health,info,liquibase,env
      base-path: /api
dodgame:
  player:
    max-characters: 10