server:
  port: 8090
spring:
  application:
    name: dod
  cloud:
    config:
      enabled: false
  cache:
    type: simple
  liquibase:
    contexts: test
    drop-first: true
  sql:
    init:
      continue-on-error: true

  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:mysql://db:3306/dodcore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: example
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 20000 #20s
      idle-timeout: 300000 #5m
      max-lifetime: 600000 #10m
      initialization-fail-timeout: -1
      validation-timeout: 1000 #1s
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        show_sql: true
        use_sql_comments: true
        format_sql: true
        cache:
          use_second_level_cache: false
    open-in-view: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
