## Use this profile when running spring dev tools
spring:
  liquibase:
    contexts: test
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:mysql://localhost:3306/dodcoreDB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dodgame
logging:
  level:
    root: INFO
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG
    dk.dodgame.rules: DEBUG