## Use this profile when running spring dev tools
spring:
  liquibase:
    contexts: test
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:mysql://localhost:3306/dodcoreDB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dodgame