name: build and verify
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test-verify:
    env:
      USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Build and test
        if: github.event_name != 'pull_request'
        run: ./gradlew test
      - name: Cache SonarCloud packages
        if: github.event_name == 'pull_request'  && github.actor != 'dependabot[bot]'
        uses: actions/cache@v3.0.11
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        run: ./gradlew :b:test --tests '*ResourceApiDocTest' :b:build :b:jDB
      - name: Verify
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: ./gradlew :b:test jacocoTestCoverageVerification sonar --warn -DincludeTests="any()" -DexcludeTests="none()"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: JUnit Report
        if: success() || failure() && github.actor != 'dependabot[bot]'
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Unit Tests
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Prepare semantic-release
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        run: |
          npm clean-install
          git branch
      - name: Do semantic-release
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
        run: npx semantic-release
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        run: ./gradlew jib -Djib.console=plain
      - name: Merge back to develop
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git checkout develop
          git pull
          git merge origin/main -X theirs
          git push origin develop
