name: Main CI
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  USERNAME: ${{ secrets.USERNAME }}
  GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: mpeki/build-env/pre-build@v0
        with:
          use-docker: false
      - name: Build backend
        run: ./gradlew :b:test --tests '*ResourceApiDocTest' :b:build

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: mpeki/build-env@v0
        with:
          use-java: false
      - name: Build UI docker image
        run: docker-compose build ui

  test-backend-regression:
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - uses: mpeki/build-env@v0
      - name: run regression tests
        run: ./gradlew :b:test
      - name: Cache SonarCloud packages
        if: github.event_name == 'pull_request'  && github.actor != 'dependabot[bot]'
        uses: actions/cache@v3.0.11
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: JUnit Report - Integration Tests
        if: success() || failure() && github.actor != 'dependabot[bot]'
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Unit Tests
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false

  test-backend-integration:
    runs-on: ubuntu-latest
    needs: [test-backend-regression]
    steps:
      - uses: mpeki/build-env@v0
      - name: Build
        run: ./gradlew :b:test --tests '*ResourceApiDocTest' :b:build :b:jDB
      - name: Integration Test
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: ./gradlew :b:test -DincludeTests="integration" -DexcludeTests="all()"
      - name: JUnit Report - Integration Tests
        if: success() || failure() && github.actor != 'dependabot[bot]'
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Unit Tests
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false

  release:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }} 
    runs-on: ubuntu-latest
    needs: [test-backend-integration]
    steps:
    - uses: mpeki/build-env@v0
      with:
        use-docker: true
        docker-user: ${{ secrets.DOCKERHUB_USER }}
        docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Prepare semantic-release
      run: |
        npm clean-install
        git branch
    - name: Do semantic-release
      run: npx semantic-release
    - name: Build and push API Docker image
      run: ./gradlew jib -Djib.console=plain
    - name: Build and push UI Docker image
      run: ./gradlew :f:pushUIC
    - name: Merge back to develop
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git fetch
        git checkout develop
        git merge origin/main -X theirs
        git push origin develop
