name: Qodana
on:
  workflow_dispatch:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]
env:
  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
