name: CI
on:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
      - 'DOD-*'
  pull_request:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
  workflow_dispatch:
jobs:
  verify-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and verify
        run: ./gradlew build sonarqube --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
      - name: Prepare semantic-release
        run: npm install
      - name: Do semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
        run: npx semantic-release
