name: Release and publish
on:
  workflow_run:
    workflows: [ "build and verify" ]
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
    types:
      - completed
jobs:
  release-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: '0'
      - run: git branch
      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout branch
        run: git checkout ${{ github.event.workflow_run.head_branch }}; git pull
      - name: Check branch
        run: git rev-parse --abbrev-ref HEAD
      - name: Prepare semantic-release
        run: npm install
      - name: Do semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
        run: npx semantic-release
      - name: Build and push Docker image
        run: ./gradlew jib -Djib.console=plain
