name: Release and publish
on:
  workflow_run:
    workflows: [ "build and verify" ]
    branches:
      - 'main'
      - 'develop'
    types:
      - completed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  release-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Release checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Prepare semantic-release
        run: |
          npm clean-install
          git checkout main; git pull
          git checkout ${{ github.event.workflow_run.head_branch }}
      - name: Do semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
        run: npx semantic-release
      - name: Build and push Docker image
        run: ./gradlew jib -Djib.console=plain
      - name: Merge back to develop
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch
          git checkout develop
          git merge origin/master -X theirs
          git push develop

          
