name: Release and publish
on:
  workflow_run:
    workflows: [ "build and verify" ]
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
    types:
      - completed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  release-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Branch info
        run: |
          echo "Branch from github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Branch from GITHUB_REF: ${GITHUB_REF#refs/heads/}"
      - name: Release checkout
        uses: actions/checkout@v3
        with:
          ref: ${GITHUB_REF#refs/heads/}
          fetch-depth: '0'
      - run: |
          git fetch origin main
          git checkout main
          git merge origin/main
          git checkout ${GITHUB_REF#refs/heads/}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Prepare semantic-release
        run: npm clean-install
      - name: Do semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
        run: npx semantic-release
      - name: Build and push Docker image
        run: ./gradlew jib -Djib.console=plain
