name: SonarCloud analysis
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  pull-requests: read
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: mpeki/build-env/pre-build@v1.0.6
        with:
          use-docker: true
      - name: Test
        run: ./gradlew :b:test
      - name: Analyze 'backend' with SonarCloud
        run: ./gradlew sonar
